service: hapi-serverless

provider:
  name: aws
  runtime: java8
  # region: eg us-east-1
  # profile: eg my-awscli-profile

package:
  artifact: target/hapi-serverless.jar

functions:
  hapiParser:
    handler: com.whitebrick.hapi.function.Parser
    events:
      - http:
          path: /
          method: post

plugins:
  - serverless-offline
custom:
  serverless-offline:
    useDocker: true
    noTimeout: true
